#!/bin/bash

sudo yum install -y git

#setup git config
git config --global user.name "fliiiix"
git config --global user.email "de-ch@hotmail.de"

##push default config
git config --global push.default simple
