#!/bin/bash

# for dcraw and cjpge
sudo dnf install -y dcraw libjpeg-turbo-utils 


sudo tee /usr/local/bin/rawtojpg << EOF
#!/bin/bash
for image in *.CR2  
do 
    dcraw -c -q 0 -w -H 5 -b 8 \$image | cjpeg -quality 80 > \${image%.CR2}.jpg
done
EOF

sudo chmod +x /usr/local/bin/rawtojpg
