#!/bin/bash

sudo yum install -y scrot

mkdir -p ~/Pictures/screenshots

sudo tee /usr/local/bin/screenshot << EOF
#!/bin/bash
sleep 0.1
scrot '%Y-%m-%d--%s_\$wx\$h.png' -e 'mv \$f ~/Pictures/screenshots' 
EOF

sudo chmod +x /usr/local/bin/screenshot
