---
- hosts: all
  become: yes
  tasks:
  - name: enable flatpak hub
    ansible.builtin.shell:
      cmd: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
  - name: install signal
    ansible.builtin.shell:
      cmd: flatpak install --assumeyes flathub org.signal.Signal
  - name: create start script
    template: src=../config/scripts/signal.tpl dest=/usr/local/bin/signal
  - name: ensure file that the script has the right permisions
    file: path=/usr/local/bin/signal owner=root group=root mode=0755

