---
- hosts: all
  tasks:
  - name: download sublime_text and check checksum
    get_url:
      url: http://download.sublimetext.com/sublime_text_build_4152_x64.tar.xz
      dest: /tmp/sublime_text.tar.xz
      checksum: md5:37667127bfba8355de03d27e58bec1b6
  - name: create directory to unpack
    become: yes
    ansible.builtin.file:
      path: /usr/local/src/sublime_text_4
      state: directory
  - name: unpack sublime_text
    become: yes
    unarchive: src=/tmp/sublime_text.tar.xz dest=/usr/local/src/sublime_text_4
  - name: create bin symlink
    become: yes
    ansible.builtin.file:
      src: /usr/local/src/sublime_text_4/sublime_text/sublime_text
      dest: /usr/local/bin/subl
      state: link
  # I think there should be a smarter way than c&p from subl_hidpi.yml
  - name: ensure that the subl config dir exist (needs to run after subl.yml)
    file: path={{ ansible_env.HOME }}/.config/sublime-text-3/Packages/User state=directory
  - name: copy config
    vars:
      is_high_dpi: False
    template:
        src: ../config/configuration/Preferences.sublime-settings.tpl
        dest: "{{ ansible_env.HOME }}/.config/sublime-text-3/Packages/User/Preferences.sublime-settings"
