alias ll='ls -la'
alias lh='ls -lah'
alias ...='cd ../..'
alias rake='noglob rake'
alias flushdns='dscacheutil -flushcache'
alias gl='git log --graph --full-history --all --color --pretty=format:"%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s"'
